name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git submodule add https://github.com/jothepro/doxygen-awesome-css.git ./doxygen/theme/doxygen-awesome && cd ./doxygen/theme/doxygen-awesome && git checkout v2.2.0
      - uses: langroodi/doxygenize@v1.6.1
        with:
          htmloutput: './html/'