var annotated_dup =
[
    [ "client", "namespaceclient.html", [
      [ "DefaultTimeLimit", "classclient_1_1_default_time_limit.html", null ],
      [ "PlayerInfo", "classclient_1_1_player_info.html", null ],
      [ "Resources", "classclient_1_1_resources.html", null ],
      [ "Tile", "classclient_1_1_tile.html", null ],
      [ "ZappyClient", "classclient_1_1_zappy_client.html", "classclient_1_1_zappy_client" ]
    ] ],
    [ "decisionTree", "namespacedecision_tree.html", [
      [ "ActionNode", "classdecision_tree_1_1_action_node.html", "classdecision_tree_1_1_action_node" ],
      [ "DecisionNode", "classdecision_tree_1_1_decision_node.html", "classdecision_tree_1_1_decision_node" ]
    ] ],
    [ "GUI", "namespace_g_u_i.html", [
      [ "ActionData", "class_g_u_i_1_1_action_data.html", "class_g_u_i_1_1_action_data" ],
      [ "Actions", "class_g_u_i_1_1_actions.html", "class_g_u_i_1_1_actions" ],
      [ "Args", "struct_g_u_i_1_1_args.html", "struct_g_u_i_1_1_args" ],
      [ "ArgsParser", "class_g_u_i_1_1_args_parser.html", "class_g_u_i_1_1_args_parser" ],
      [ "Cell", "class_g_u_i_1_1_cell.html", "class_g_u_i_1_1_cell" ],
      [ "Chrono", "class_g_u_i_1_1_chrono.html", "class_g_u_i_1_1_chrono" ],
      [ "Coms", "class_g_u_i_1_1_coms.html", "class_g_u_i_1_1_coms" ],
      [ "config", "struct_g_u_i_1_1config.html", "struct_g_u_i_1_1config" ],
      [ "Config", "class_g_u_i_1_1_config.html", "class_g_u_i_1_1_config" ],
      [ "Core", "class_g_u_i_1_1_core.html", "class_g_u_i_1_1_core" ],
      [ "Egg", "class_g_u_i_1_1_egg.html", "class_g_u_i_1_1_egg" ],
      [ "GraphicalFactory", "class_g_u_i_1_1_graphical_factory.html", "class_g_u_i_1_1_graphical_factory" ],
      [ "ICamera", "class_g_u_i_1_1_i_camera.html", "class_g_u_i_1_1_i_camera" ],
      [ "ICell", "class_g_u_i_1_1_i_cell.html", "class_g_u_i_1_1_i_cell" ],
      [ "IClock", "class_g_u_i_1_1_i_clock.html", "class_g_u_i_1_1_i_clock" ],
      [ "IConfig", "class_g_u_i_1_1_i_config.html", "class_g_u_i_1_1_i_config" ],
      [ "ICore", "class_g_u_i_1_1_i_core.html", "class_g_u_i_1_1_i_core" ],
      [ "IGraphicalModule", "class_g_u_i_1_1_i_graphical_module.html", "class_g_u_i_1_1_i_graphical_module" ],
      [ "IMap", "class_g_u_i_1_1_i_map.html", "class_g_u_i_1_1_i_map" ],
      [ "INetwork", "class_g_u_i_1_1_i_network.html", "class_g_u_i_1_1_i_network" ],
      [ "IParser", "class_g_u_i_1_1_i_parser.html", "class_g_u_i_1_1_i_parser" ],
      [ "Map", "class_g_u_i_1_1_map.html", "class_g_u_i_1_1_map" ],
      [ "modelConfig", "struct_g_u_i_1_1model_config.html", "struct_g_u_i_1_1model_config" ],
      [ "ModelData", "struct_g_u_i_1_1_model_data.html", "struct_g_u_i_1_1_model_data" ],
      [ "Network", "class_g_u_i_1_1_network.html", "class_g_u_i_1_1_network" ],
      [ "Parser", "class_g_u_i_1_1_parser.html", "class_g_u_i_1_1_parser" ],
      [ "Player", "class_g_u_i_1_1_player.html", "class_g_u_i_1_1_player" ],
      [ "RayLib", "class_g_u_i_1_1_ray_lib.html", "class_g_u_i_1_1_ray_lib" ],
      [ "RayLibCamera", "class_g_u_i_1_1_ray_lib_camera.html", "class_g_u_i_1_1_ray_lib_camera" ],
      [ "Vector2f", "struct_g_u_i_1_1_vector2f.html", "struct_g_u_i_1_1_vector2f" ],
      [ "Vector2i", "class_g_u_i_1_1_vector2i.html", "class_g_u_i_1_1_vector2i" ],
      [ "Vector3f", "class_g_u_i_1_1_vector3f.html", "class_g_u_i_1_1_vector3f" ]
    ] ],
    [ "__attribute__", "struct____attribute____.html", "struct____attribute____" ],
    [ "ai_command_t", "structai__command__t.html", "structai__command__t" ],
    [ "connection_s", "structconnection__s.html", "structconnection__s" ],
    [ "database_s", "structdatabase__s.html", "structdatabase__s" ],
    [ "egg_s", "structegg__s.html", "structegg__s" ],
    [ "incantation_data_s", "structincantation__data__s.html", "structincantation__data__s" ],
    [ "incantation_requirement_s", "structincantation__requirement__s.html", "structincantation__requirement__s" ],
    [ "IPlayer", "class_i_player.html", "class_i_player" ],
    [ "map_cell_t", "structmap__cell__t.html", "structmap__cell__t" ],
    [ "map_t", "structmap__t.html", "structmap__t" ],
    [ "player_s", "structplayer__s.html", "structplayer__s" ],
    [ "pos_s", "structpos__s.html", "structpos__s" ],
    [ "resource_s", "unionresource__s.html", "unionresource__s" ],
    [ "Scene", "class_scene.html", "class_scene" ],
    [ "string_buffer_s", "structstring__buffer__s.html", "structstring__buffer__s" ],
    [ "team_s", "structteam__s.html", "structteam__s" ],
    [ "vector_template_t", "structvector__template__t.html", "structvector__template__t" ],
    [ "zappy_s", "structzappy__s.html", "structzappy__s" ]
];